baseURL = 'https://cuisine.restanrm.fr/'
languageCode = 'fr-fr'
title = 'Recettes de Cuisine'
theme = "PaperMod"

[menu]
  [[menu.main]]
    name = "Accueil"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Desserts"
    url = "/desserts/"
    weight = 3
  [[menu.main]]
    name = "Apéro"
    url = "/apero/"
    weight = 2
  [[menu.main]]
    name = "Pâtes"
    url = "/pates/"
    weight = 2
  [[menu.main]]
    name = "Petit-dej"
    url = "/petit-dej/"
    weight = 3
  [[menu.main]]
    name = "Plats"
    url = "/plats/"
    weight = 2
  [[menu.main]]
    name = "Sauces"
    url = "/sauces/"
    weight = 2
  [[menu.main]]
    name = "Tartes"
    url = "/tartes/"
    weight = 2
